version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  dbPostgres:
    image: postgres
    container_name: dbPostgresv1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: mydb
  actualBackend:
    image: prateekkumarsingh/dbms-theory-backend:v5
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - dbPostgres
  actualFrontend:
    image: prateekkumarsingh/dbms-theory-frontend:v5
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - actualBackend
  ankitFrontend:
     image: prateekkumarsingh/docker-react-v1-ankit-on-fire:v1
     restart: always
     ports:
      - 3001:80
     depends_on:
      - actualBackend
