# Generated by Django 4.1.7 on 2023-02-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionalDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("left", models.CharField(max_length=200)),
                ("right", models.CharField(max_length=200)),
            ],
        ),
    ]
