# Generated by Django 4.1.7 on 2023-02-25 13:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0002_functionaldependency"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetOfAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attributes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1), blank=True, size=None
                    ),
                ),
            ],
        ),
    ]
