# Generated by Django 4.1.7 on 2023-02-25 13:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0003_setofattributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setofattributes",
            name="attributes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
