# Generated by Django 4.1.7 on 2023-02-25 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0011_remove_setofattributes_ok_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeeksModel",
        ),
    ]
