# Generated by Django 4.1.7 on 2023-02-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0013_setofattributes_functionaldependency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setofattributes",
            name="FunctionalDependency",
        ),
        migrations.CreateModel(
            name="CombineSetOfAttributesFunctionalDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FunctionalDependency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Functional_Dependency2",
                        to="apis.functionaldependency",
                    ),
                ),
                (
                    "attributes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Set_Of_Attributes",
                        to="apis.setofattributes",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="setofattributes",
            name="FunctionalDependency",
            field=models.ManyToManyField(
                related_name="Functional_Dependency1", to="apis.functionaldependency"
            ),
        ),
    ]
