# Generated by Django 4.1.7 on 2023-02-25 19:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0015_remove_setofattributes_functionaldependency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setofattributes",
            name="FunctionalDependency",
        ),
        migrations.AlterField(
            model_name="setofattributes",
            name="attributes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1),
                default=list,
                max_length=20,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="setofattributes",
            name="FunctionalDependency",
            field=models.ManyToManyField(to="apis.functionaldependency"),
        ),
    ]
