# Generated by Django 4.1.7 on 2023-02-27 10:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0017_alter_setofattributes_attributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionaldependency",
            name="left",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="functionaldependency",
            name="right",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="setofattributes",
            name="attributes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100000),
                default=list,
                max_length=100000,
                size=None,
            ),
        ),
    ]
