# Generated by Django 4.1.7 on 2023-02-27 10:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0018_alter_functionaldependency_left_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionaldependency",
            name="left",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10000),
                default=list,
                max_length=10000,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="functionaldependency",
            name="right",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10000),
                default=list,
                max_length=10000,
                size=None,
            ),
        ),
    ]
